// personagem
const character = {
  id: "1",
  name: "Rick Sanchez",
  status: "Alive",
  type: "",
  gender: "Male",
  species: "Human",
  origin: {
    name: "Earth (C-137)",
    id: "1",
  },
  location: {
    name: "Citadel of Ricks",
    id: "3",
  },
  image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
  episode: [
    {
      id: "1",
      name: "Pilot",
      episode: "S01E01",
    },
    {
      id: "2",
      name: "Lawnmower Dog",
      episode: "S01E02",
    },
    {
      id: "3",
      name: "Anatomy Park",
      episode: "S01E03",
    },
    {
      id: "4",
      name: "M. Night Shaym-Aliens!",
      episode: "S01E04",
    },
    {
      id: "5",
      name: "Meeseeks and Destroy",
      episode: "S01E05",
    },
    {
      id: "6",
      name: "Rick Potion #9",
      episode: "S01E06",
    },
    {
      id: "7",
      name: "Raising Gazorpazorp",
      episode: "S01E07",
    },
    {
      id: "8",
      name: "Rixty Minutes",
      episode: "S01E08",
    },
    {
      id: "9",
      name: "Something Ricked This Way Comes",
      episode: "S01E09",
    },
    {
      id: "10",
      name: "Close Rick-counters of the Rick Kind",
      episode: "S01E10",
    },
    {
      id: "11",
      name: "Ricksy Business",
      episode: "S01E11",
    },
    {
      id: "12",
      name: "A Rickle in Time",
      episode: "S02E01",
    },
    {
      id: "13",
      name: "Mortynight Run",
      episode: "S02E02",
    },
    {
      id: "14",
      name: "Auto Erotic Assimilation",
      episode: "S02E03",
    },
    {
      id: "15",
      name: "Total Rickall",
      episode: "S02E04",
    },
    {
      id: "16",
      name: "Get Schwifty",
      episode: "S02E05",
    },
    {
      id: "17",
      name: "The Ricks Must Be Crazy",
      episode: "S02E06",
    },
    {
      id: "18",
      name: "Big Trouble in Little Sanchez",
      episode: "S02E07",
    },
    {
      id: "19",
      name: "Interdimensional Cable 2: Tempting Fate",
      episode: "S02E08",
    },
    {
      id: "20",
      name: "Look Who's Purging Now",
      episode: "S02E09",
    },
    {
      id: "21",
      name: "The Wedding Squanchers",
      episode: "S02E10",
    },
    {
      id: "22",
      name: "The Rickshank Rickdemption",
      episode: "S03E01",
    },
    {
      id: "23",
      name: "Rickmancing the Stone",
      episode: "S03E02",
    },
    {
      id: "24",
      name: "Pickle Rick",
      episode: "S03E03",
    },
    {
      id: "25",
      name: "Vindicators 3: The Return of Worldender",
      episode: "S03E04",
    },
    {
      id: "26",
      name: "The Whirly Dirly Conspiracy",
      episode: "S03E05",
    },
    {
      id: "27",
      name: "Rest and Ricklaxation",
      episode: "S03E06",
    },
    {
      id: "28",
      name: "The Ricklantis Mixup",
      episode: "S03E07",
    },
    {
      id: "29",
      name: "Morty's Mind Blowers",
      episode: "S03E08",
    },
    {
      id: "30",
      name: "The ABC's of Beth",
      episode: "S03E09",
    },
    {
      id: "31",
      name: "The Rickchurian Mortydate",
      episode: "S03E10",
    },
    {
      id: "32",
      name: "Edge of Tomorty: Rick, Die, Rickpeat",
      episode: "S04E01",
    },
    {
      id: "33",
      name: "The Old Man and the Seat",
      episode: "S04E02",
    },
    {
      id: "34",
      name: "One Crew Over the Crewcoo's Morty",
      episode: "S04E03",
    },
    {
      id: "35",
      name: "Claw and Hoarder: Special Ricktim's Morty",
      episode: "S04E04",
    },
    {
      id: "36",
      name: "Rattlestar Ricklactica",
      episode: "S04E05",
    },
    {
      id: "37",
      name: "Never Ricking Morty",
      episode: "S04E06",
    },
    {
      id: "38",
      name: "Promortyus",
      episode: "S04E07",
    },
    {
      id: "39",
      name: "The Vat of Acid Episode",
      episode: "S04E08",
    },
    {
      id: "40",
      name: "Childrick of Mort",
      episode: "S04E09",
    },
    {
      id: "41",
      name: "Star Mort: Rickturn of the Jerri",
      episode: "S04E10",
    },
    {
      id: "42",
      name: "Mort Dinner Rick Andre",
      episode: "S05E01",
    },
    {
      id: "43",
      name: "Mortyplicity",
      episode: "S05E02",
    },
    {
      id: "44",
      name: "A Rickconvenient Mort",
      episode: "S05E03",
    },
    {
      id: "45",
      name: "Rickdependence Spray",
      episode: "S05E04",
    },
    {
      id: "46",
      name: "Amortycan Grickfitti",
      episode: "S05E05",
    },
    {
      id: "47",
      name: "Rick & Morty's Thanksploitation Spectacular",
      episode: "S05E06",
    },
    {
      id: "48",
      name: "Gotron Jerrysis Rickvangelion",
      episode: "S05E07",
    },
    {
      id: "49",
      name: "Rickternal Friendshine of the Spotless Mort",
      episode: "S05E08",
    },
    {
      id: "50",
      name: "Forgetting Sarick Mortshall",
      episode: "S05E09",
    },
    {
      id: "51",
      name: "Rickmurai Jack",
      episode: "S05E10",
    },
  ],
};

// personagens
const characters = {
  info: {
    count: 826,
    pages: 42,
    next: "https://rickandmortyapi.com/api/character/?page=20",
    prev: "https://rickandmortyapi.com/api/character/?page=18",
  },
  results: [
    {
      id: 1,
      name: "Rick Sanchez",
      status: "Alive",
      species: "Human",
      type: "",
      gender: "Male",
      origin: {
        name: "Earth (C-137)",
        url: "https://rickandmortyapi.com/api/location/1",
      },
      location: {
        name: "Citadel of Ricks",
        url: "https://rickandmortyapi.com/api/location/3",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
      episode: [
        "https://rickandmortyapi.com/api/episode/1",
        "https://rickandmortyapi.com/api/episode/2",
        "https://rickandmortyapi.com/api/episode/3",
        "https://rickandmortyapi.com/api/episode/4",
        "https://rickandmortyapi.com/api/episode/5",
        "https://rickandmortyapi.com/api/episode/6",
        "https://rickandmortyapi.com/api/episode/7",
        "https://rickandmortyapi.com/api/episode/8",
        "https://rickandmortyapi.com/api/episode/9",
        "https://rickandmortyapi.com/api/episode/10",
        "https://rickandmortyapi.com/api/episode/11",
        "https://rickandmortyapi.com/api/episode/12",
        "https://rickandmortyapi.com/api/episode/13",
        "https://rickandmortyapi.com/api/episode/14",
        "https://rickandmortyapi.com/api/episode/15",
        "https://rickandmortyapi.com/api/episode/16",
        "https://rickandmortyapi.com/api/episode/17",
        "https://rickandmortyapi.com/api/episode/18",
        "https://rickandmortyapi.com/api/episode/19",
        "https://rickandmortyapi.com/api/episode/20",
        "https://rickandmortyapi.com/api/episode/21",
        "https://rickandmortyapi.com/api/episode/22",
        "https://rickandmortyapi.com/api/episode/23",
        "https://rickandmortyapi.com/api/episode/24",
        "https://rickandmortyapi.com/api/episode/25",
        "https://rickandmortyapi.com/api/episode/26",
        "https://rickandmortyapi.com/api/episode/27",
        "https://rickandmortyapi.com/api/episode/28",
        "https://rickandmortyapi.com/api/episode/29",
        "https://rickandmortyapi.com/api/episode/30",
        "https://rickandmortyapi.com/api/episode/31",
        "https://rickandmortyapi.com/api/episode/32",
        "https://rickandmortyapi.com/api/episode/33",
        "https://rickandmortyapi.com/api/episode/34",
        "https://rickandmortyapi.com/api/episode/35",
        "https://rickandmortyapi.com/api/episode/36",
        "https://rickandmortyapi.com/api/episode/37",
        "https://rickandmortyapi.com/api/episode/38",
        "https://rickandmortyapi.com/api/episode/39",
        "https://rickandmortyapi.com/api/episode/40",
        "https://rickandmortyapi.com/api/episode/41",
        "https://rickandmortyapi.com/api/episode/42",
        "https://rickandmortyapi.com/api/episode/43",
        "https://rickandmortyapi.com/api/episode/44",
        "https://rickandmortyapi.com/api/episode/45",
        "https://rickandmortyapi.com/api/episode/46",
        "https://rickandmortyapi.com/api/episode/47",
        "https://rickandmortyapi.com/api/episode/48",
        "https://rickandmortyapi.com/api/episode/49",
        "https://rickandmortyapi.com/api/episode/50",
        "https://rickandmortyapi.com/api/episode/51",
      ],
      url: "https://rickandmortyapi.com/api/character/1",
      created: "2017-11-04T18:48:46.250Z",
    },
    {
      id: 2,
      name: "Morty Smith",
      status: "Alive",
      species: "Human",
      type: "",
      gender: "Male",
      origin: { name: "unknown", url: "" },
      location: {
        name: "Citadel of Ricks",
        url: "https://rickandmortyapi.com/api/location/3",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
      episode: [
        "https://rickandmortyapi.com/api/episode/1",
        "https://rickandmortyapi.com/api/episode/2",
        "https://rickandmortyapi.com/api/episode/3",
        "https://rickandmortyapi.com/api/episode/4",
        "https://rickandmortyapi.com/api/episode/5",
        "https://rickandmortyapi.com/api/episode/6",
        "https://rickandmortyapi.com/api/episode/7",
        "https://rickandmortyapi.com/api/episode/8",
        "https://rickandmortyapi.com/api/episode/9",
        "https://rickandmortyapi.com/api/episode/10",
        "https://rickandmortyapi.com/api/episode/11",
        "https://rickandmortyapi.com/api/episode/12",
        "https://rickandmortyapi.com/api/episode/13",
        "https://rickandmortyapi.com/api/episode/14",
        "https://rickandmortyapi.com/api/episode/15",
        "https://rickandmortyapi.com/api/episode/16",
        "https://rickandmortyapi.com/api/episode/17",
        "https://rickandmortyapi.com/api/episode/18",
        "https://rickandmortyapi.com/api/episode/19",
        "https://rickandmortyapi.com/api/episode/20",
        "https://rickandmortyapi.com/api/episode/21",
        "https://rickandmortyapi.com/api/episode/22",
        "https://rickandmortyapi.com/api/episode/23",
        "https://rickandmortyapi.com/api/episode/24",
        "https://rickandmortyapi.com/api/episode/25",
        "https://rickandmortyapi.com/api/episode/26",
        "https://rickandmortyapi.com/api/episode/27",
        "https://rickandmortyapi.com/api/episode/28",
        "https://rickandmortyapi.com/api/episode/29",
        "https://rickandmortyapi.com/api/episode/30",
        "https://rickandmortyapi.com/api/episode/31",
        "https://rickandmortyapi.com/api/episode/32",
        "https://rickandmortyapi.com/api/episode/33",
        "https://rickandmortyapi.com/api/episode/34",
        "https://rickandmortyapi.com/api/episode/35",
        "https://rickandmortyapi.com/api/episode/36",
        "https://rickandmortyapi.com/api/episode/37",
        "https://rickandmortyapi.com/api/episode/38",
        "https://rickandmortyapi.com/api/episode/39",
        "https://rickandmortyapi.com/api/episode/40",
        "https://rickandmortyapi.com/api/episode/41",
        "https://rickandmortyapi.com/api/episode/42",
        "https://rickandmortyapi.com/api/episode/43",
        "https://rickandmortyapi.com/api/episode/44",
        "https://rickandmortyapi.com/api/episode/45",
        "https://rickandmortyapi.com/api/episode/46",
        "https://rickandmortyapi.com/api/episode/47",
        "https://rickandmortyapi.com/api/episode/48",
        "https://rickandmortyapi.com/api/episode/49",
        "https://rickandmortyapi.com/api/episode/50",
        "https://rickandmortyapi.com/api/episode/51",
      ],
      url: "https://rickandmortyapi.com/api/character/2",
      created: "2017-11-04T18:50:21.651Z",
    },
    {
      id: 3,
      name: "Morty Smith",
      status: "Alive",
      species: "Human",
      type: "",
      gender: "Male",
      origin: { name: "unknown", url: "" },
      location: {
        name: "Citadel of Ricks",
        url: "https://rickandmortyapi.com/api/location/3",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
      episode: [
        "https://rickandmortyapi.com/api/episode/1",
        "https://rickandmortyapi.com/api/episode/2",
        "https://rickandmortyapi.com/api/episode/3",
        "https://rickandmortyapi.com/api/episode/4",
        "https://rickandmortyapi.com/api/episode/5",
        "https://rickandmortyapi.com/api/episode/6",
        "https://rickandmortyapi.com/api/episode/7",
        "https://rickandmortyapi.com/api/episode/8",
        "https://rickandmortyapi.com/api/episode/9",
        "https://rickandmortyapi.com/api/episode/10",
        "https://rickandmortyapi.com/api/episode/11",
        "https://rickandmortyapi.com/api/episode/12",
        "https://rickandmortyapi.com/api/episode/13",
        "https://rickandmortyapi.com/api/episode/14",
        "https://rickandmortyapi.com/api/episode/15",
        "https://rickandmortyapi.com/api/episode/16",
        "https://rickandmortyapi.com/api/episode/17",
        "https://rickandmortyapi.com/api/episode/18",
        "https://rickandmortyapi.com/api/episode/19",
        "https://rickandmortyapi.com/api/episode/20",
        "https://rickandmortyapi.com/api/episode/21",
        "https://rickandmortyapi.com/api/episode/22",
        "https://rickandmortyapi.com/api/episode/23",
        "https://rickandmortyapi.com/api/episode/24",
        "https://rickandmortyapi.com/api/episode/25",
        "https://rickandmortyapi.com/api/episode/26",
        "https://rickandmortyapi.com/api/episode/27",
        "https://rickandmortyapi.com/api/episode/28",
        "https://rickandmortyapi.com/api/episode/29",
        "https://rickandmortyapi.com/api/episode/30",
        "https://rickandmortyapi.com/api/episode/31",
        "https://rickandmortyapi.com/api/episode/32",
        "https://rickandmortyapi.com/api/episode/33",
        "https://rickandmortyapi.com/api/episode/34",
        "https://rickandmortyapi.com/api/episode/35",
        "https://rickandmortyapi.com/api/episode/36",
        "https://rickandmortyapi.com/api/episode/37",
        "https://rickandmortyapi.com/api/episode/38",
        "https://rickandmortyapi.com/api/episode/39",
        "https://rickandmortyapi.com/api/episode/40",
        "https://rickandmortyapi.com/api/episode/41",
        "https://rickandmortyapi.com/api/episode/42",
        "https://rickandmortyapi.com/api/episode/43",
        "https://rickandmortyapi.com/api/episode/44",
        "https://rickandmortyapi.com/api/episode/45",
        "https://rickandmortyapi.com/api/episode/46",
        "https://rickandmortyapi.com/api/episode/47",
        "https://rickandmortyapi.com/api/episode/48",
        "https://rickandmortyapi.com/api/episode/49",
        "https://rickandmortyapi.com/api/episode/50",
        "https://rickandmortyapi.com/api/episode/51",
      ],
      url: "https://rickandmortyapi.com/api/character/2",
      created: "2017-11-04T18:50:21.651Z",
    },
    {
      id: 4,
      name: "Morty Smith",
      status: "Alive",
      species: "Human",
      type: "",
      gender: "Male",
      origin: { name: "unknown", url: "" },
      location: {
        name: "Citadel of Ricks",
        url: "https://rickandmortyapi.com/api/location/3",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
      episode: [
        "https://rickandmortyapi.com/api/episode/1",
        "https://rickandmortyapi.com/api/episode/2",
        "https://rickandmortyapi.com/api/episode/3",
        "https://rickandmortyapi.com/api/episode/4",
        "https://rickandmortyapi.com/api/episode/5",
        "https://rickandmortyapi.com/api/episode/6",
        "https://rickandmortyapi.com/api/episode/7",
        "https://rickandmortyapi.com/api/episode/8",
        "https://rickandmortyapi.com/api/episode/9",
        "https://rickandmortyapi.com/api/episode/10",
        "https://rickandmortyapi.com/api/episode/11",
        "https://rickandmortyapi.com/api/episode/12",
        "https://rickandmortyapi.com/api/episode/13",
        "https://rickandmortyapi.com/api/episode/14",
        "https://rickandmortyapi.com/api/episode/15",
        "https://rickandmortyapi.com/api/episode/16",
        "https://rickandmortyapi.com/api/episode/17",
        "https://rickandmortyapi.com/api/episode/18",
        "https://rickandmortyapi.com/api/episode/19",
        "https://rickandmortyapi.com/api/episode/20",
        "https://rickandmortyapi.com/api/episode/21",
        "https://rickandmortyapi.com/api/episode/22",
        "https://rickandmortyapi.com/api/episode/23",
        "https://rickandmortyapi.com/api/episode/24",
        "https://rickandmortyapi.com/api/episode/25",
        "https://rickandmortyapi.com/api/episode/26",
        "https://rickandmortyapi.com/api/episode/27",
        "https://rickandmortyapi.com/api/episode/28",
        "https://rickandmortyapi.com/api/episode/29",
        "https://rickandmortyapi.com/api/episode/30",
        "https://rickandmortyapi.com/api/episode/31",
        "https://rickandmortyapi.com/api/episode/32",
        "https://rickandmortyapi.com/api/episode/33",
        "https://rickandmortyapi.com/api/episode/34",
        "https://rickandmortyapi.com/api/episode/35",
        "https://rickandmortyapi.com/api/episode/36",
        "https://rickandmortyapi.com/api/episode/37",
        "https://rickandmortyapi.com/api/episode/38",
        "https://rickandmortyapi.com/api/episode/39",
        "https://rickandmortyapi.com/api/episode/40",
        "https://rickandmortyapi.com/api/episode/41",
        "https://rickandmortyapi.com/api/episode/42",
        "https://rickandmortyapi.com/api/episode/43",
        "https://rickandmortyapi.com/api/episode/44",
        "https://rickandmortyapi.com/api/episode/45",
        "https://rickandmortyapi.com/api/episode/46",
        "https://rickandmortyapi.com/api/episode/47",
        "https://rickandmortyapi.com/api/episode/48",
        "https://rickandmortyapi.com/api/episode/49",
        "https://rickandmortyapi.com/api/episode/50",
        "https://rickandmortyapi.com/api/episode/51",
      ],
      url: "https://rickandmortyapi.com/api/character/2",
      created: "2017-11-04T18:50:21.651Z",
    },
    {
      id: 5,
      name: "Morty Smith",
      status: "Alive",
      species: "Human",
      type: "",
      gender: "Male",
      origin: { name: "unknown", url: "" },
      location: {
        name: "Citadel of Ricks",
        url: "https://rickandmortyapi.com/api/location/3",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
      episode: [
        "https://rickandmortyapi.com/api/episode/1",
        "https://rickandmortyapi.com/api/episode/2",
        "https://rickandmortyapi.com/api/episode/3",
        "https://rickandmortyapi.com/api/episode/4",
        "https://rickandmortyapi.com/api/episode/5",
        "https://rickandmortyapi.com/api/episode/6",
        "https://rickandmortyapi.com/api/episode/7",
        "https://rickandmortyapi.com/api/episode/8",
        "https://rickandmortyapi.com/api/episode/9",
        "https://rickandmortyapi.com/api/episode/10",
        "https://rickandmortyapi.com/api/episode/11",
        "https://rickandmortyapi.com/api/episode/12",
        "https://rickandmortyapi.com/api/episode/13",
        "https://rickandmortyapi.com/api/episode/14",
        "https://rickandmortyapi.com/api/episode/15",
        "https://rickandmortyapi.com/api/episode/16",
        "https://rickandmortyapi.com/api/episode/17",
        "https://rickandmortyapi.com/api/episode/18",
        "https://rickandmortyapi.com/api/episode/19",
        "https://rickandmortyapi.com/api/episode/20",
        "https://rickandmortyapi.com/api/episode/21",
        "https://rickandmortyapi.com/api/episode/22",
        "https://rickandmortyapi.com/api/episode/23",
        "https://rickandmortyapi.com/api/episode/24",
        "https://rickandmortyapi.com/api/episode/25",
        "https://rickandmortyapi.com/api/episode/26",
        "https://rickandmortyapi.com/api/episode/27",
        "https://rickandmortyapi.com/api/episode/28",
        "https://rickandmortyapi.com/api/episode/29",
        "https://rickandmortyapi.com/api/episode/30",
        "https://rickandmortyapi.com/api/episode/31",
        "https://rickandmortyapi.com/api/episode/32",
        "https://rickandmortyapi.com/api/episode/33",
        "https://rickandmortyapi.com/api/episode/34",
        "https://rickandmortyapi.com/api/episode/35",
        "https://rickandmortyapi.com/api/episode/36",
        "https://rickandmortyapi.com/api/episode/37",
        "https://rickandmortyapi.com/api/episode/38",
        "https://rickandmortyapi.com/api/episode/39",
        "https://rickandmortyapi.com/api/episode/40",
        "https://rickandmortyapi.com/api/episode/41",
        "https://rickandmortyapi.com/api/episode/42",
        "https://rickandmortyapi.com/api/episode/43",
        "https://rickandmortyapi.com/api/episode/44",
        "https://rickandmortyapi.com/api/episode/45",
        "https://rickandmortyapi.com/api/episode/46",
        "https://rickandmortyapi.com/api/episode/47",
        "https://rickandmortyapi.com/api/episode/48",
        "https://rickandmortyapi.com/api/episode/49",
        "https://rickandmortyapi.com/api/episode/50",
        "https://rickandmortyapi.com/api/episode/51",
      ],
      url: "https://rickandmortyapi.com/api/character/2",
      created: "2017-11-04T18:50:21.651Z",
    },
    {
      id: 6,
      name: "Morty Smith",
      status: "Alive",
      species: "Human",
      type: "",
      gender: "Male",
      origin: { name: "unknown", url: "" },
      location: {
        name: "Citadel of Ricks",
        url: "https://rickandmortyapi.com/api/location/3",
      },
      image: "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
      episode: [
        "https://rickandmortyapi.com/api/episode/1",
        "https://rickandmortyapi.com/api/episode/2",
        "https://rickandmortyapi.com/api/episode/3",
        "https://rickandmortyapi.com/api/episode/4",
        "https://rickandmortyapi.com/api/episode/5",
        "https://rickandmortyapi.com/api/episode/6",
        "https://rickandmortyapi.com/api/episode/7",
        "https://rickandmortyapi.com/api/episode/8",
        "https://rickandmortyapi.com/api/episode/9",
        "https://rickandmortyapi.com/api/episode/10",
        "https://rickandmortyapi.com/api/episode/11",
        "https://rickandmortyapi.com/api/episode/12",
        "https://rickandmortyapi.com/api/episode/13",
        "https://rickandmortyapi.com/api/episode/14",
        "https://rickandmortyapi.com/api/episode/15",
        "https://rickandmortyapi.com/api/episode/16",
        "https://rickandmortyapi.com/api/episode/17",
        "https://rickandmortyapi.com/api/episode/18",
        "https://rickandmortyapi.com/api/episode/19",
        "https://rickandmortyapi.com/api/episode/20",
        "https://rickandmortyapi.com/api/episode/21",
        "https://rickandmortyapi.com/api/episode/22",
        "https://rickandmortyapi.com/api/episode/23",
        "https://rickandmortyapi.com/api/episode/24",
        "https://rickandmortyapi.com/api/episode/25",
        "https://rickandmortyapi.com/api/episode/26",
        "https://rickandmortyapi.com/api/episode/27",
        "https://rickandmortyapi.com/api/episode/28",
        "https://rickandmortyapi.com/api/episode/29",
        "https://rickandmortyapi.com/api/episode/30",
        "https://rickandmortyapi.com/api/episode/31",
        "https://rickandmortyapi.com/api/episode/32",
        "https://rickandmortyapi.com/api/episode/33",
        "https://rickandmortyapi.com/api/episode/34",
        "https://rickandmortyapi.com/api/episode/35",
        "https://rickandmortyapi.com/api/episode/36",
        "https://rickandmortyapi.com/api/episode/37",
        "https://rickandmortyapi.com/api/episode/38",
        "https://rickandmortyapi.com/api/episode/39",
        "https://rickandmortyapi.com/api/episode/40",
        "https://rickandmortyapi.com/api/episode/41",
        "https://rickandmortyapi.com/api/episode/42",
        "https://rickandmortyapi.com/api/episode/43",
        "https://rickandmortyapi.com/api/episode/44",
        "https://rickandmortyapi.com/api/episode/45",
        "https://rickandmortyapi.com/api/episode/46",
        "https://rickandmortyapi.com/api/episode/47",
        "https://rickandmortyapi.com/api/episode/48",
        "https://rickandmortyapi.com/api/episode/49",
        "https://rickandmortyapi.com/api/episode/50",
        "https://rickandmortyapi.com/api/episode/51",
      ],
      url: "https://rickandmortyapi.com/api/character/2",
      created: "2017-11-04T18:50:21.651Z",
    },
  ],
};

// dimensao
const dimension = {
  id: 1,
  name: "Earth (C-137)",
  type: "Planet",
  dimension: "Dimension C-137",
  residents: [
    "https://rickandmortyapi.com/api/character/38",
    "https://rickandmortyapi.com/api/character/45",
    "https://rickandmortyapi.com/api/character/71",
    "https://rickandmortyapi.com/api/character/82",
    "https://rickandmortyapi.com/api/character/83",
    "https://rickandmortyapi.com/api/character/92",
    "https://rickandmortyapi.com/api/character/112",
    "https://rickandmortyapi.com/api/character/114",
    "https://rickandmortyapi.com/api/character/116",
    "https://rickandmortyapi.com/api/character/117",
    "https://rickandmortyapi.com/api/character/120",
    "https://rickandmortyapi.com/api/character/127",
    "https://rickandmortyapi.com/api/character/155",
    "https://rickandmortyapi.com/api/character/169",
    "https://rickandmortyapi.com/api/character/175",
    "https://rickandmortyapi.com/api/character/179",
    "https://rickandmortyapi.com/api/character/186",
    "https://rickandmortyapi.com/api/character/201",
    "https://rickandmortyapi.com/api/character/216",
    "https://rickandmortyapi.com/api/character/239",
    "https://rickandmortyapi.com/api/character/271",
    "https://rickandmortyapi.com/api/character/302",
    "https://rickandmortyapi.com/api/character/303",
    "https://rickandmortyapi.com/api/character/338",
    "https://rickandmortyapi.com/api/character/343",
    "https://rickandmortyapi.com/api/character/356",
    "https://rickandmortyapi.com/api/character/394",
  ],
  url: "https://rickandmortyapi.com/api/location/1",
  created: "2017-11-10T12:42:04.162Z",
};

// dimensões
const dimensions = {
  info: {
    count: 126,
    pages: 7,
    next: "https://rickandmortyapi.com/api/location?page=2",
    prev: null,
  },
  results: [
    {
      id: 1,
      name: "Earth (C-137)",
      type: "Planet",
      dimension: "Dimension C-137",
      residents: [
        "https://rickandmortyapi.com/api/character/38",
        "https://rickandmortyapi.com/api/character/45",
        "https://rickandmortyapi.com/api/character/71",
        "https://rickandmortyapi.com/api/character/82",
        "https://rickandmortyapi.com/api/character/83",
        "https://rickandmortyapi.com/api/character/92",
        "https://rickandmortyapi.com/api/character/112",
        "https://rickandmortyapi.com/api/character/114",
        "https://rickandmortyapi.com/api/character/116",
        "https://rickandmortyapi.com/api/character/117",
        "https://rickandmortyapi.com/api/character/120",
        "https://rickandmortyapi.com/api/character/127",
        "https://rickandmortyapi.com/api/character/155",
        "https://rickandmortyapi.com/api/character/169",
        "https://rickandmortyapi.com/api/character/175",
        "https://rickandmortyapi.com/api/character/179",
        "https://rickandmortyapi.com/api/character/186",
        "https://rickandmortyapi.com/api/character/201",
        "https://rickandmortyapi.com/api/character/216",
        "https://rickandmortyapi.com/api/character/239",
        "https://rickandmortyapi.com/api/character/271",
        "https://rickandmortyapi.com/api/character/302",
        "https://rickandmortyapi.com/api/character/303",
        "https://rickandmortyapi.com/api/character/338",
        "https://rickandmortyapi.com/api/character/343",
        "https://rickandmortyapi.com/api/character/356",
        "https://rickandmortyapi.com/api/character/394",
      ],
      url: "https://rickandmortyapi.com/api/location/1",
      created: "2017-11-10T12:42:04.162Z",
    },
    {
      id: 2,
      name: "Abadango",
      type: "Cluster",
      dimension: "unknown",
      residents: ["https://rickandmortyapi.com/api/character/6"],
      url: "https://rickandmortyapi.com/api/location/2",
      created: "2017-11-10T13:06:38.182Z",
    },
    {
      id: 3,
      name: "Citadel of Ricks",
      type: "Space station",
      dimension: "unknown",
      residents: [
        "https://rickandmortyapi.com/api/character/8",
        "https://rickandmortyapi.com/api/character/14",
        "https://rickandmortyapi.com/api/character/15",
        "https://rickandmortyapi.com/api/character/18",
        "https://rickandmortyapi.com/api/character/21",
        "https://rickandmortyapi.com/api/character/22",
        "https://rickandmortyapi.com/api/character/27",
        "https://rickandmortyapi.com/api/character/42",
        "https://rickandmortyapi.com/api/character/43",
        "https://rickandmortyapi.com/api/character/44",
        "https://rickandmortyapi.com/api/character/48",
        "https://rickandmortyapi.com/api/character/53",
        "https://rickandmortyapi.com/api/character/56",
        "https://rickandmortyapi.com/api/character/61",
        "https://rickandmortyapi.com/api/character/69",
        "https://rickandmortyapi.com/api/character/72",
        "https://rickandmortyapi.com/api/character/73",
        "https://rickandmortyapi.com/api/character/74",
        "https://rickandmortyapi.com/api/character/77",
        "https://rickandmortyapi.com/api/character/78",
        "https://rickandmortyapi.com/api/character/85",
        "https://rickandmortyapi.com/api/character/86",
        "https://rickandmortyapi.com/api/character/95",
        "https://rickandmortyapi.com/api/character/118",
        "https://rickandmortyapi.com/api/character/119",
        "https://rickandmortyapi.com/api/character/123",
        "https://rickandmortyapi.com/api/character/135",
        "https://rickandmortyapi.com/api/character/143",
        "https://rickandmortyapi.com/api/character/152",
        "https://rickandmortyapi.com/api/character/164",
        "https://rickandmortyapi.com/api/character/165",
        "https://rickandmortyapi.com/api/character/187",
        "https://rickandmortyapi.com/api/character/200",
        "https://rickandmortyapi.com/api/character/206",
        "https://rickandmortyapi.com/api/character/209",
        "https://rickandmortyapi.com/api/character/220",
        "https://rickandmortyapi.com/api/character/229",
        "https://rickandmortyapi.com/api/character/231",
        "https://rickandmortyapi.com/api/character/235",
        "https://rickandmortyapi.com/api/character/267",
        "https://rickandmortyapi.com/api/character/278",
        "https://rickandmortyapi.com/api/character/281",
        "https://rickandmortyapi.com/api/character/283",
        "https://rickandmortyapi.com/api/character/284",
        "https://rickandmortyapi.com/api/character/285",
        "https://rickandmortyapi.com/api/character/286",
        "https://rickandmortyapi.com/api/character/287",
        "https://rickandmortyapi.com/api/character/288",
        "https://rickandmortyapi.com/api/character/289",
        "https://rickandmortyapi.com/api/character/291",
        "https://rickandmortyapi.com/api/character/295",
        "https://rickandmortyapi.com/api/character/298",
        "https://rickandmortyapi.com/api/character/299",
        "https://rickandmortyapi.com/api/character/322",
        "https://rickandmortyapi.com/api/character/325",
        "https://rickandmortyapi.com/api/character/328",
        "https://rickandmortyapi.com/api/character/330",
        "https://rickandmortyapi.com/api/character/345",
        "https://rickandmortyapi.com/api/character/359",
        "https://rickandmortyapi.com/api/character/366",
        "https://rickandmortyapi.com/api/character/378",
        "https://rickandmortyapi.com/api/character/385",
        "https://rickandmortyapi.com/api/character/392",
        "https://rickandmortyapi.com/api/character/461",
        "https://rickandmortyapi.com/api/character/462",
        "https://rickandmortyapi.com/api/character/463",
        "https://rickandmortyapi.com/api/character/464",
        "https://rickandmortyapi.com/api/character/465",
        "https://rickandmortyapi.com/api/character/466",
        "https://rickandmortyapi.com/api/character/472",
        "https://rickandmortyapi.com/api/character/473",
        "https://rickandmortyapi.com/api/character/474",
        "https://rickandmortyapi.com/api/character/475",
        "https://rickandmortyapi.com/api/character/476",
        "https://rickandmortyapi.com/api/character/477",
        "https://rickandmortyapi.com/api/character/478",
        "https://rickandmortyapi.com/api/character/479",
        "https://rickandmortyapi.com/api/character/480",
        "https://rickandmortyapi.com/api/character/481",
        "https://rickandmortyapi.com/api/character/482",
        "https://rickandmortyapi.com/api/character/483",
        "https://rickandmortyapi.com/api/character/484",
        "https://rickandmortyapi.com/api/character/485",
        "https://rickandmortyapi.com/api/character/486",
        "https://rickandmortyapi.com/api/character/487",
        "https://rickandmortyapi.com/api/character/488",
        "https://rickandmortyapi.com/api/character/489",
        "https://rickandmortyapi.com/api/character/2",
        "https://rickandmortyapi.com/api/character/1",
        "https://rickandmortyapi.com/api/character/801",
        "https://rickandmortyapi.com/api/character/802",
        "https://rickandmortyapi.com/api/character/803",
        "https://rickandmortyapi.com/api/character/804",
        "https://rickandmortyapi.com/api/character/805",
        "https://rickandmortyapi.com/api/character/806",
        "https://rickandmortyapi.com/api/character/810",
        "https://rickandmortyapi.com/api/character/811",
        "https://rickandmortyapi.com/api/character/812",
        "https://rickandmortyapi.com/api/character/819",
        "https://rickandmortyapi.com/api/character/820",
        "https://rickandmortyapi.com/api/character/818",
      ],
      url: "https://rickandmortyapi.com/api/location/3",
      created: "2017-11-10T13:08:13.191Z",
    },
  ],
};

// localização
const location = {
  id: "4",
  name: "Worldender's lair",
  type: "Planet",
  dimension: "unknown",
  residents: [
    {
      id: "10",
      name: "Alan Rails",
      image: "https://rickandmortyapi.com/api/character/avatar/10.jpeg",
    },
    {
      id: "81",
      name: "Crocubot",
      image: "https://rickandmortyapi.com/api/character/avatar/81.jpeg",
    },
    {
      id: "208",
      name: "Logic",
      image: "https://rickandmortyapi.com/api/character/avatar/208.jpeg",
    },
    {
      id: "226",
      name: "Million Ants",
      image: "https://rickandmortyapi.com/api/character/avatar/226.jpeg",
    },
    {
      id: "340",
      name: "Supernova",
      image: "https://rickandmortyapi.com/api/character/avatar/340.jpeg",
    },
    {
      id: "362",
      name: "Traflorkian",
      image: "https://rickandmortyapi.com/api/character/avatar/362.jpeg",
    },
    {
      id: "375",
      name: "Vance Maximus",
      image: "https://rickandmortyapi.com/api/character/avatar/375.jpeg",
    },
    {
      id: "382",
      name: "Worldender",
      image: "https://rickandmortyapi.com/api/character/avatar/382.jpeg",
    },
    {
      id: "395",
      name: "Greebybobe",
      image: "https://rickandmortyapi.com/api/character/avatar/395.jpeg",
    },
  ],
};

const data = {
  character,
  characters,
  dimension,
  dimensions,
  location,
};

export default data;
